In [2]:
import os 
print(os.getcwd())

C:\Users\gabri\Downloads

In [13]:
import pandas as pd
import numpy as np
import os
#Q1:Defina um diretório de trabalho 
f='C:/Users/gabri/OneDrive'
os.chdir(f)
print(os.getcwd())

C:\Users\gabri\OneDrive

In [14]:
#Q2:Importe os 3 arquivos de dados para o Python

#arquivo 1
A='https://gitlab.com/lemaufpb/dspy/-/raw/main/data/dim_escola.xlsx'
d_escolas=pd.read_excel(A,sheet_name='dados',
                        names=['cod_escola','cod_municipio','cod_rede','localizacao','nome_escola','situacao_funcionamento'])
d_escolas

,cod_escola,cod_municipio,cod_rede,localizacao,nome_escola,situacao_funcionamento
0,25000012,2501005,3,1,EMEF JOAO ALVES,1
1,25000020,2502003,3,1,CRECHE INTEGRADA MARIA DO SOCORRO LINHARES,2
2,25000047,2502003,2,1,ECI NOSSA SENHORA DA CONCEICAO,1
3,25000055,2502003,2,1,EEEFM AMERICO MAIA,1
4,25000063,2502003,3,1,EMEIF PREFEITO PLINIO FORTE MAIA,1
...,...,...,...,...,...,...
4611,25291920,2505238,3,1,CRECHE INFANTIL NEMEZIO AUGUSTO DE MEIRELES,1
4612,25292927,2505238,3,2,EMEF JOAO CALIXTO DOS SANTOS,1
4613,25302949,2514800,3,2,ESCOLA MUNICIPAL ANA CELIA DE QUEIROZ,2
4614,25307924,2501575,3,1,CEMEB PROFESSORA MARLY BARBOSA DE ALMEIDA - TI...,1
4615,25309935,2506400,3,1,EMEIF PROFESSORA CARMEM SILVIA ALVES DA SILVA,1

In [15]:
#arquivo 2
B='https://gitlab.com/lemaufpb/dspy/-/raw/main/data/fato_rendimento_escolar.csv'
rend_escolar=pd.read_csv(B, sep='|',skiprows=5, na_values='-').\
rename(columns={'Ano':'Anos','Código da Escola':'cod_escola',
                             'Taxa de Abandono no Ensino Médio (%)':'Taxa_de_Abandono'})
rend_escolar['Taxa_de_Abandono'] = rend_escolar['Taxa_de_Abandono'].str.replace(',','.').astype(float)
rend_escolar

      Anos  cod_escola  Taxa_de_Abandono
0     2014    25000047               NaN
1     2015    25000047              13.2
2     2016    25000047              12.7
3     2017    25000047               5.5
4     2018    25000047              10.8
...    ...         ...               ...
3514  2017    25284940               2.1
3515  2018    25284940               1.4
3516  2019    25284940               0.0
3517  2020    25284940               0.0
3518  2021    25284940               0.3

[3519 rows x 3 columns]

In [16]:
#arquivo 3
l='C:/Users/gabri/OneDrive/prova2/RELATORIO_DTB_BRASIL_MUNICIPIO (1).xls'

colunas=['UF','Nome_UF','cod_Região_Intermediária','Nome_Região_Intermediária',
         'cod_Região_Imediata','Nome_Região_Imediata','cod_Mesorregião',
         'Nome_Mesorregião','cod_Microrregião','Nome_Microrregião',
         'Município','cod_municipio','Nome_Município' ]
rdm=pd.read_excel(l,names=colunas)
rdm['id'] =rdm.index
rdm

,UF,Nome_UF,cod_Região_Intermediária,Nome_Região_Intermediária,cod_Região_Imediata,Nome_Região_Imediata,cod_Mesorregião,Nome_Mesorregião,cod_Microrregião,Nome_Microrregião,Município,cod_municipio,Nome_Município,id
0,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,2,Leste Rondoniense,6,Cacoal,15,1100015,Alta Floresta D'Oeste,0
1,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,2,Leste Rondoniense,6,Cacoal,379,1100379,Alto Alegre dos Parecis,1
2,11,Rondônia,1101,Porto Velho,110002,Ariquemes,2,Leste Rondoniense,3,Ariquemes,403,1100403,Alto Paraíso,2
3,11,Rondônia,1102,Ji-Paraná,110004,Ji-Paraná,2,Leste Rondoniense,5,Alvorada D'Oeste,346,1100346,Alvorada D'Oeste,3
4,11,Rondônia,1101,Porto Velho,110002,Ariquemes,2,Leste Rondoniense,3,Ariquemes,23,1100023,Ariquemes,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5565,52,Goiás,5201,Goiânia,520002,Anápolis,5,Sul Goiano,16,Pires do Rio,22005,5222005,Vianópolis,5565
5566,52,Goiás,5202,Itumbiara,520009,Piracanjuba,5,Sul Goiano,15,Meia Ponte,22054,5222054,Vicentinópolis,5566
5567,52,Goiás,5206,Luziânia - Águas Lindas de Goiás,520022,Flores de Goiás,4,Leste Goiano,12,Entorno de Brasília,22203,5222203,Vila Boa,5567
5568,52,Goiás,5205,Porangatu - Uruaçu,520018,Ceres - Rialma - Goianésia,4,Leste Goiano,12,Entorno de Brasília,22302,5222302,Vila Propício,5568
5569,53,Distrito Federal,5301,Distrito Federal,530001,Distrito Federal,1,Distrito Federal,1,Brasília,108,5300108,Brasília,5569

In [17]:
# Ao final faça uma inspeção nos dados usando .info() em cada objeto.

d_escolas.info()

rend_escolar.info()

rdm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4616 entries, 0 to 4615
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   cod_escola              4616 non-null   int64
 1   cod_municipio           4616 non-null   int64
 2   cod_rede                4616 non-null   int64
 3   localizacao             4616 non-null   int64
 4   nome_escola             4616 non-null   object
 5   situacao_funcionamento  4616 non-null   int64
dtypes: int64(5), object(1)
memory usage: 216.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3519 entries, 0 to 3518
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Anos              3519 non-null   int64
 1   cod_escola        3519 non-null   int64
 2   Taxa_de_Abandono  3115 non-null   float64
dtypes: float64(1), int64(2)
memory usage: 82.6 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   UF                         5570 non-null   int64
 1   Nome_UF                    5570 non-null   object
 2   cod_Região_Intermediária   5570 non-null   int64
 3   Nome_Região_Intermediária  5570 non-null   object
 4   cod_Região_Imediata        5570 non-null   int64
 5   Nome_Região_Imediata       5570 non-null   object
 6   cod_Mesorregião            5570 non-null   int64
 7   Nome_Mesorregião           5570 non-null   object
 8   cod_Microrregião           5570 non-null   int64
 9   Nome_Microrregião          5570 non-null   object
 10  Município                  5570 non-null   int64
 11  cod_municipio              5570 non-null   int64
 12  Nome_Município             5570 non-null   object
 13  id                         5570 non-null   int64
dtypes: int64(8), object(6)
memory usage: 609.3+ KB

In [18]:
#Q3:Crie um objeto chamado df a partir da junção das tabelas dim_escola e dtb e dos seguintes filtros:
#escolas da rede estadual de ensino; em atividade; no estado da Paraíba.

p=pd.merge(rdm,d_escolas , on='cod_municipio', how='left')
df=p.query('Nome_UF=="Paraíba"').\
query('cod_rede==2').\
query('situacao_funcionamento == 1')                                                        
df

,UF,Nome_UF,cod_Região_Intermediária,Nome_Região_Intermediária,cod_Região_Imediata,Nome_Região_Imediata,cod_Mesorregião,Nome_Mesorregião,cod_Microrregião,Nome_Microrregião,Município,cod_municipio,Nome_Município,id,cod_escola,cod_rede,localizacao,nome_escola,situacao_funcionamento
1243,25,Paraíba,2503,Patos,250009,Patos,1,Sertão Paraibano,7,Serra do Teixeira,106,2500106,Água Branca,1242,25033204.0,2.0,1.0,ECI EEM JOSE NOMINANDO,1.0
1267,25,Paraíba,2503,Patos,250010,Itaporanga,1,Sertão Paraibano,5,Piancó,205,2500205,Aguiar,1243,25023489.0,2.0,1.0,ECI EEM AGENOR MENDES PEDROSA,1.0
1284,25,Paraíba,2502,Campina Grande,250005,Campina Grande,3,Agreste Paraibano,15,Brejo Paraibano,304,2500304,Alagoa Grande,1244,25062638.0,2.0,1.0,EEEFM PADRE HILDON BANDEIRA,1.0
1286,25,Paraíba,2502,Campina Grande,250005,Campina Grande,3,Agreste Paraibano,15,Brejo Paraibano,304,2500304,Alagoa Grande,1244,25062670.0,2.0,1.0,EEEF DE DEMONSTRACAO ALAGOA GRANDE,1.0
1291,25,Paraíba,2502,Campina Grande,250005,Campina Grande,3,Agreste Paraibano,15,Brejo Paraibano,304,2500304,Alagoa Grande,1244,25062816.0,2.0,1.0,ECIT OSWALDO TRIGUEIRO DE ALBUQUERQUE MELO,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5828,25,Paraíba,2503,Patos,250009,Patos,2,Borborema,8,Seridó Ocidental Paraibano,17100,2517100,Várzea,1461,25040600.0,2.0,1.0,EEEM PROF ODILON DE FIGUEIREDO,1.0
5840,25,Paraíba,2504,Sousa - Cajazeiras,250014,Sousa,1,Sertão Paraibano,3,Sousa,17209,2517209,Vieirópolis,1462,25019740.0,2.0,1.0,EEEM MARIA MOREIRA PINTO,1.0
5845,25,Paraíba,2504,Sousa - Cajazeiras,250014,Sousa,1,Sertão Paraibano,3,Sousa,17209,2517209,Vieirópolis,1462,25126342.0,2.0,2.0,EEEF ANTONIA MARIA ANUNCIACAO DONA DONINHA,1.0
5846,25,Paraíba,2503,Patos,250009,Patos,1,Sertão Paraibano,3,Sousa,5501,2505501,Vista Serrana,1463,25014226.0,2.0,1.0,EEEFM MANOEL MEDEIROS DE ARAUJO,1.0
5855,25,Paraíba,2502,Campina Grande,250007,Monteiro,2,Borborema,10,Cariri Ocidental,17407,2517407,Zabelê,1464,25048368.0,2.0,1.0,EEEFM PROF MARIA CELESTE DO NASCIMENTO,1.0

In [19]:
#Q4:Junte ao objeto df, os dados da tabela fato_rendimento_escolar, filtrando o período de 2015 a 2021.

df2=pd.merge(df,rend_escolar, on='cod_escola', how='inner')
df2=df2.query('Anos!=2014').replace(np.nan,0)
df2

,UF,Nome_UF,cod_Região_Intermediária,Nome_Região_Intermediária,cod_Região_Imediata,Nome_Região_Imediata,cod_Mesorregião,Nome_Mesorregião,cod_Microrregião,Nome_Microrregião,...,cod_municipio,Nome_Município,id,cod_escola,cod_rede,localizacao,nome_escola,situacao_funcionamento,Anos,Taxa_de_Abandono
1,25,Paraíba,2503,Patos,250009,Patos,1,Sertão Paraibano,7,Serra do Teixeira,...,2500106,Água Branca,1242,25033204.0,2.0,1.0,ECI EEM JOSE NOMINANDO,1.0,2015,7.4
2,25,Paraíba,2503,Patos,250009,Patos,1,Sertão Paraibano,7,Serra do Teixeira,...,2500106,Água Branca,1242,25033204.0,2.0,1.0,ECI EEM JOSE NOMINANDO,1.0,2016,11.8
3,25,Paraíba,2503,Patos,250009,Patos,1,Sertão Paraibano,7,Serra do Teixeira,...,2500106,Água Branca,1242,25033204.0,2.0,1.0,ECI EEM JOSE NOMINANDO,1.0,2017,3.0
4,25,Paraíba,2503,Patos,250009,Patos,1,Sertão Paraibano,7,Serra do Teixeira,...,2500106,Água Branca,1242,25033204.0,2.0,1.0,ECI EEM JOSE NOMINANDO,1.0,2018,10.0
5,25,Paraíba,2503,Patos,250009,Patos,1,Sertão Paraibano,7,Serra do Teixeira,...,2500106,Água Branca,1242,25033204.0,2.0,1.0,ECI EEM JOSE NOMINANDO,1.0,2019,10.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3314,25,Paraíba,2502,Campina Grande,250007,Monteiro,2,Borborema,10,Cariri Ocidental,...,2517407,Zabelê,1464,25048368.0,2.0,1.0,EEEFM PROF MARIA CELESTE DO NASCIMENTO,1.0,2017,20.5
3315,25,Paraíba,2502,Campina Grande,250007,Monteiro,2,Borborema,10,Cariri Ocidental,...,2517407,Zabelê,1464,25048368.0,2.0,1.0,EEEFM PROF MARIA CELESTE DO NASCIMENTO,1.0,2018,8.8
3316,25,Paraíba,2502,Campina Grande,250007,Monteiro,2,Borborema,10,Cariri Ocidental,...,2517407,Zabelê,1464,25048368.0,2.0,1.0,EEEFM PROF MARIA CELESTE DO NASCIMENTO,1.0,2019,1.6
3317,25,Paraíba,2502,Campina Grande,250007,Monteiro,2,Borborema,10,Cariri Ocidental,...,2517407,Zabelê,1464,25048368.0,2.0,1.0,EEEFM PROF MARIA CELESTE DO NASCIMENTO,1.0,2020,0.0
3318,25,Paraíba,2502,Campina Grande,250007,Monteiro,2,Borborema,10,Cariri Ocidental,...,2517407,Zabelê,1464,25048368.0,2.0,1.0,EEEFM PROF MARIA CELESTE DO NASCIMENTO,1.0,2021,0.0

In [20]:
#Q5:Imprima uma relação com o nome da escola, nome do município e a taxa de abandono das 20 escolas com
#maior nível de abandono escolar em 2021.
q5=df2.query('Anos==2021').\
filter(items=['nome_escola','Nome_Município','Taxa_de_Abandono']).\
sort_values('Taxa_de_Abandono', ascending= False).\
head(20)
q5

,nome_escola,Nome_Município,Taxa_de_Abandono
1745,EEEFM BENEDITA TARGINO MARANHAO,João Pessoa,39.6
1580,EEEF PROF MARIA GENY DE SOUSA TIMOTEO,João Pessoa,38.1
3097,EEEFM ARLINDO RAMALHO,Solânea,31.4
2784,EEEFM JOAO SILVEIRA GUIMARAES,São Bento,29.1
361,EEEFM PROF JOAQUIM UMBELINO,Bom Jesus,27.6
656,EEEFM POETA CARLOS DRUMOND DE ANDRADE,Campina Grande,24.7
2227,ENE D EXPEDITO E DE OLIVEIRA,Patos,24.6
871,EEEFM MAJOR VENEZIANO VITAL DO REGO,Campina Grande,23.6
1914,EEEF II E EJA UMBELINA GARCEZ,Mamanguape,23.1
997,EEEFM PROF JOAO DA CUNHA VINAGRE,Conde,20.9
1596,EEEM PROF ORLANDO CAVALCANTI GOMES,João Pessoa,19.8
332,EEEFM AMERICO MAIA,Belém do Brejo do Cruz,19.7
1301,EEEM ADALGISA TEODULO DA FONSECA,Itaporanga,19.6
2891,E EST DE CURSO NORMAL EM NIVEL MEDIO SAO JOSE,São José de Piranhas,18.7
1958,EEIEF INDIO PEDRO MAXIMO DE LIMA,Marcação,18.1
1557,EEEF PROFESSOR JOAO JOSE DA COSTA,João Pessoa,17.7
1516,ECI HORACIO DE ALMEIDA,João Pessoa,17.3
2030,EEEFM ANTONIO MOACIR DANTAS CAVALCANTI,Maturéia,16.9
1396,ECIT RAUL MACHADO,João Pessoa,16.8
204,EEIEFM AKAJUTIBIRO,Baía da Traição,16.1

In [21]:
#Q6:Imprima uma relação com o nome da escola, nome do município, nome da mesorregião e a taxa de abandono
#das escolas com o maior nível de abandono escolar em 2021 em cada microrregião do estado da Paraíba.
q6=df2.sort_values('Taxa_de_Abandono', ascending=False).\
query('Anos==2021').\
filter(items=['nome_escola','Nome_Município','Nome_Mesorregião','Taxa_de_Abandono','Nome_Microrregião'])
q6.drop_duplicates(subset=['Nome_Microrregião'])

,nome_escola,Nome_Município,Nome_Mesorregião,Taxa_de_Abandono,Nome_Microrregião
1745,EEEFM BENEDITA TARGINO MARANHAO,João Pessoa,Mata Paraibana,39.6,João Pessoa
3097,EEEFM ARLINDO RAMALHO,Solânea,Agreste Paraibano,31.4,Curimataú Oriental
2784,EEEFM JOAO SILVEIRA GUIMARAES,São Bento,Sertão Paraibano,29.1,Catolé do Rocha
361,EEEFM PROF JOAQUIM UMBELINO,Bom Jesus,Sertão Paraibano,27.6,Cajazeiras
656,EEEFM POETA CARLOS DRUMOND DE ANDRADE,Campina Grande,Agreste Paraibano,24.7,Campina Grande
2227,ENE D EXPEDITO E DE OLIVEIRA,Patos,Sertão Paraibano,24.6,Patos
1914,EEEF II E EJA UMBELINA GARCEZ,Mamanguape,Mata Paraibana,23.1,Litoral Norte
1301,EEEM ADALGISA TEODULO DA FONSECA,Itaporanga,Sertão Paraibano,19.6,Itaporanga
2030,EEEFM ANTONIO MOACIR DANTAS CAVALCANTI,Maturéia,Sertão Paraibano,16.9,Serra do Teixeira
71,ECIT RENATO RIBEIRO COUTINHO,Alhandra,Mata Paraibana,16.0,Litoral Sul
1869,EEEF PREF JOSE ANTONIO NEVES,Logradouro,Agreste Paraibano,13.1,Guarabira
228,ENE PROF PEDRO A DE ALMEIDA,Bananeiras,Agreste Paraibano,12.8,Brejo Paraibano
1041,EEEFM FLAVIO RIBEIRO COUTINHO,Cruz do Espírito Santo,Mata Paraibana,11.9,Sapé
2074,EEEF MIGUEL SANTA CRUZ,Monteiro,Borborema,11.6,Cariri Ocidental
2327,EEEFM FELIPE TIAGO GOMES,Picuí,Borborema,10.1,Seridó Oriental Paraibano
583,EEEFM MARIA SOLEDADE ASSIS FREITAS,Cajazeirinhas,Sertão Paraibano,9.6,Sousa
1783,EEEFM DOM ADAUTO,Juarez Távora,Agreste Paraibano,8.9,Itabaiana
2593,EEEM FENELON NOBREGA,Salgadinho,Borborema,6.2,Seridó Ocidental Paraibano
260,EEE FUNDAMENTAL E MEDIO MELQUIADES TEJO,Barra de São Miguel,Borborema,6.1,Cariri Oriental
2046,ECI MARIA JOSE DE SOUZA,Montadas,Agreste Paraibano,5.6,Esperança
118,ECI EEM MONSENHOR JOSE PAULINO,Arara,Agreste Paraibano,5.4,Curimataú Ocidental
2304,ENE SANTO ANTONIO,Piancó,Sertão Paraibano,4.6,Piancó
2100,ECIT FRANCISCO DE ALBUQUERQUE MONTENEGRO,Natuba,Agreste Paraibano,2.1,Umbuzeiro

In [36]:
#Q7:Imprima uma relação com o código da escola, nome da escola, localização e a diferença da taxa de abandono
#das 10 escolas com as maiores diferenças das taxas de abandono entre os anos de 2019 (antes da pandemia)
#e 2021 (no período da pandemia).

ano_19=df2.query('Anos==2019')
ano_21=df2.query('Anos==2021')
td=ano_19.merge(ano_21,on=['cod_escola','nome_escola','localizacao'])
q7=td.filter(items=['cod_escola','nome_escola','localizacao'])
q7['diff_2019|2021']=td['Taxa_de_Abandono_y']-td['Taxa_de_Abandono_x']
q7.sort_values('diff_2019|2021', ascending=False, inplace=True)

q7.head(10)

,cod_escola,nome_escola,localizacao,diff_2019|2021
370,25003844.0,EEEFM JOAO SILVEIRA GUIMARAES,1.0,21.4
48,25006029.0,EEEFM PROF JOAQUIM UMBELINO,1.0,19.6
87,25072056.0,EEEFM POETA CARLOS DRUMOND DE ANDRADE,1.0,18.6
298,25021427.0,ENE D EXPEDITO E DE OLIVEIRA,1.0,17.2
410,25060406.0,EEEFM ARLINDO RAMALHO,1.0,16.8
235,25123696.0,EEEFM BENEDITA TARGINO MARANHAO,1.0,16.1
175,25030566.0,EEEM ADALGISA TEODULO DA FONSECA,1.0,14.5
213,25094629.0,EEEF PROF MARIA GENY DE SOUSA TIMOTEO,1.0,14.2
141,25088572.0,EEEFM FLAVIO RIBEIRO COUTINHO,1.0,11.9
206,25094190.0,ECIT JOAO GOULART,1.0,11.3

In [37]:
#tabela para a questão 8 com todas as escolas 
J=pd.merge(df,rend_escolar, on='cod_escola', how='inner').\
query('Nome_UF=="Paraíba"').\
query('situacao_funcionamento == 1').\
query('Anos!=2014')

In [38]:
#Q8:Qual é o percentual de escolas com abandono escolar acima da média estadual no ano de 2021?
#calculo
#média de abandono das escolas estaduais :
media_estadual=df2.query('Anos==2021').\
filter(items=['Taxa_de_Abandono'])
d=media_estadual.mean()
print(d)

#escolas que atendem o pré-requisito de ter a média maior que a média estadual:
escolas_2021=J.query('Anos==2021').\
filter(items=['Taxa_de_Abandono'])
d2=escolas_2021[escolas_2021.Taxa_de_Abandono > 3.079565 ]
d2
len(d2)
#todas as escolas :
td_escolas=J.query('Anos==2021').\
filter(items=['Taxa_de_Abandono'])
len(td_escolas)
print(len(d2),len(td_escolas))

Taxa_de_Abandono    3.079565
dtype: float64
136 460

In [39]:
### Q8 resposta
#percetual das escolas 460-100% assim como 136-x%
q8=(len(d2)*100)/len(td_escolas)
print('O percentual de escolas com abandono escolar acima da média estadual no ano de 2021 é de',q8 ,'%.')

O percentual de escolas com abandono escolar acima da média estadual no ano de 2021 é de 29.565217391304348 %.

In [40]:
#Q9:Qual é a média da taxa de abandono escolar por ano?

media_2021=df2.query('Anos==2021').filter(items=['Taxa_de_Abandono']).mean()
print('taxa de abandono de 2021',media_2021)
print('-'*60)
media_2020=df2.query('Anos==2020 ').filter(items=['Taxa_de_Abandono']).mean()
print('taxa de abandono de 2020',media_2020)
print('-'*60)
media_2019=df2.query('Anos==2019 ').filter(items=['Taxa_de_Abandono']).mean()
print('taxa de abandono de 2019',media_2019)
print('-'*60)
media_2018=df2.query('Anos==2018 ').filter(items=['Taxa_de_Abandono']).mean()
print('taxa de abandono de 2018',media_2018)
print('-'*60)
media_2017=df2.query('Anos==2017 ').filter(items=['Taxa_de_Abandono']).mean()
print('taxa de abandono de 2017',media_2017)
print('-'*60)
media_2016=df2.query('Anos==2016 ').filter(items=['Taxa_de_Abandono']).mean()
print('taxa de abandono de 2016',media_2016)
print('-'*60)
media_2015=df2.query('Anos==2015 ').filter(items=['Taxa_de_Abandono']).mean()
print('taxa de abandono de 2015',media_2015)
print('-'*60)

taxa de abandono de 2021 Taxa_de_Abandono    3.079565
dtype: float64
------------------------------------------------------------
taxa de abandono de 2020 Taxa_de_Abandono    2.070925
dtype: float64
------------------------------------------------------------
taxa de abandono de 2019 Taxa_de_Abandono    6.956787
dtype: float64
------------------------------------------------------------
taxa de abandono de 2018 Taxa_de_Abandono    10.357275
dtype: float64
------------------------------------------------------------
taxa de abandono de 2017 Taxa_de_Abandono    12.187374
dtype: float64
------------------------------------------------------------
taxa de abandono de 2016 Taxa_de_Abandono    14.707532
dtype: float64
------------------------------------------------------------
taxa de abandono de 2015 Taxa_de_Abandono    13.634483
dtype: float64
------------------------------------------------------------

In [41]:
#Q10: Qual é a média da taxa de abandono escolar por ano e localização (rural, urbana)?
#rural('localizacao==2')
#urbana('localizacao==1')
#escolas rurais 
print('rural 2021',df2.query('localizacao==2 & Anos==2021').filter(items=['Taxa_de_Abandono']).mean())
print('rural 2020',df2.query('localizacao==2 & Anos==2020').filter(items=['Taxa_de_Abandono']).mean())
print('rural 2019',df2.query('localizacao==2 & Anos==2019').filter(items=['Taxa_de_Abandono']).mean())
print('rural 2018',df2.query('localizacao==2 & Anos==2018').filter(items=['Taxa_de_Abandono']).mean())
print('rural 2017',df2.query('localizacao==2 & Anos==2017').filter(items=['Taxa_de_Abandono']).mean())
print('rural 2016',df2.query('localizacao==2 & Anos==2016').filter(items=['Taxa_de_Abandono']).mean())
print('rural 2015',df2.query('localizacao==2 & Anos==2015').filter(items=['Taxa_de_Abandono']).mean())

print('_'*60)
  
#escolas urbanas 
print('urbana 2021',df2.query('localizacao==1 & Anos==2021').filter(items=['Taxa_de_Abandono']).mean())
print('urbana 2020',df2.query('localizacao==1 & Anos==2020').filter(items=['Taxa_de_Abandono']).mean())
print('urbana 2019',df2.query('localizacao==1 & Anos==2019').filter(items=['Taxa_de_Abandono']).mean())
print('urbana 2018',df2.query('localizacao==1 & Anos==2018').filter(items=['Taxa_de_Abandono']).mean())
print('urbana 2017',df2.query('localizacao==1 & Anos==2017').filter(items=['Taxa_de_Abandono']).mean())
print('urbana 2016',df2.query('localizacao==1 & Anos==2016').filter(items=['Taxa_de_Abandono']).mean())
print('urbana 2015',df2.query('localizacao==1 & Anos==2015').filter(items=['Taxa_de_Abandono']).mean())

rural 2021 Taxa_de_Abandono    2.534884
dtype: float64
rural 2020 Taxa_de_Abandono    1.697619
dtype: float64
rural 2019 Taxa_de_Abandono    6.597368
dtype: float64
rural 2018 Taxa_de_Abandono    9.587179
dtype: float64
rural 2017 Taxa_de_Abandono    9.745946
dtype: float64
rural 2016 Taxa_de_Abandono    14.1
dtype: float64
rural 2015 Taxa_de_Abandono    12.417647
dtype: float64
____________________________________________________________
urbana 2021 Taxa_de_Abandono    3.135731
dtype: float64
urbana 2020 Taxa_de_Abandono    2.108981
dtype: float64
urbana 2019 Taxa_de_Abandono    6.990594
dtype: float64
urbana 2018 Taxa_de_Abandono    10.433503
dtype: float64
urbana 2017 Taxa_de_Abandono    12.438997
dtype: float64
urbana 2016 Taxa_de_Abandono    14.768286
dtype: float64
urbana 2015 Taxa_de_Abandono    13.755102
dtype: float64

Q11: Com base nas análises de dados realizadas, o que é possível concluir sobre os efeitos da pandemia no nível
de abandono escolar no ensino médio?


 Com base nos dados sobre a taxa de abandono das escolas estaduais da paraíba, pode-se concluir que a taxa de abandono escolar de modo geral vem diminuindo ao longo dos anos  ,vemos esse fenômeno ao comparar as taxas de 2015 com as de 2021 que são respectivamente de 13.63% e 3.07% ,contudo, essa diminuição não é linear por ter  aumentos nos anos 2016 e 2021, mas ao comparar a taxa dos anos inicial e final dos dados temos uma queda de mais de 10%.
 No âmago pré e pós pandemia houve uma diminuição de quase 50% na taxa de abandono ao comparar 2019 com 6.95% e 2021 com 3.07%,já no período pandêmico de 2020 a 2021 houve um aumento a taxa era de 2,07% e passou a ser de 3,07% .  
 Nas escolas estaduais de localização urbanas da Paraíba temos um  aumento de 2015 para 2016 e  uma diminuição linear de 2016 à 2020 e um aumento em 2021. O mesmo fenômeno acontece nas escolas de localização Rural da Paraíba .Ao comparar a taxa de abandono das escolas urbanas  com as escolas rurais vemos que  em todo o  período da pesquisa os dados demonstram que as escolas urbanas sofrem em média mais abandonos  que as escolas rurais . 
 As mesorregiões que mais sofrem com o abandono escolar são o Agreste paraibano e o Sertão paraibano ,as escolas dessas duas mesorregiões ocupam 15 das 23  escolas com o maior nível de abandono escolar em 2021.
 
 O efeito da Pandemia nas escolas estaduais de ensino médio da Paraíba na  taxa de abandono escolar foi uma oscilação por ter uma queda significativa de 2019 para 2020  e um aumento em 2021  que não superam os valores de antes da pandemia, então pode-se concluir que até o ano de 2021 a pandemia não afetou excessivamente as taxas de abandono mas hove uma queda considerável.