In [1]:
#Q1
import os
f = 'C:/Users/gabri/OneDrive/2015'
os.chdir(f)
print(os.getcwd())

C:\Users\gabri\OneDrive\2015

In [2]:
#Q2,Q3,Q4
import pandas as pd
g='https://gitlab.com/lemaufpb/dspy/-/raw/main/data/ideb5_2015.xlsx'
df=pd.read_excel(g,nrows=100, header=None, na_values='-',skiprows=8,usecols=[0,1,2,3,4,5,71,76])
df

,0,1,2,3,4,5,71,76
0,PB,2500106,Água Branca,25033158,EMEIF MAE IAIA,Municipal,6.0,5.3
1,PB,2500106,Água Branca,25033557,EMEIF DELFINO JOSE DOS SANTOS,Municipal,6.2,4.3
2,PB,2500106,Água Branca,25033670,EMEF ANTONIO VIRGOLINO BATISTA,Municipal,NaN,5.2
3,PB,2500205,Aguiar,25023489,EEEM AGENOR MENDES PEDROSA,Estadual,NaN,3.7
4,PB,2500205,Aguiar,25023535,EMEIEFCNNM LIDIA CABRAL DE SOUSA,Municipal,NaN,3.9
...,...,...,...,...,...,...,...,...
95,PB,2501203,Areial,25061429,EMGLA GERALDO L DE ARAUJO,Municipal,4.5,4.5
96,PB,2501203,Areial,25061445,E M E F FRANCISCO APOLINARIO DA SILVA,Municipal,5.7,4.0
97,PB,2501203,Areial,25061542,GR ESC EZEQUIEL VIEIRA,Municipal,NaN,5.0
98,PB,2501203,Areial,25061593,GR ESC MODELO,Municipal,5.0,4.7
99,PB,2501203,Areial,25061607,GR ESC SEVERINO BARBOSA,Municipal,4.4,3.5

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       100 non-null    object
 1   1       100 non-null    int64
 2   2       100 non-null    object
 3   3       100 non-null    int64
 4   4       100 non-null    object
 5   5       100 non-null    object
 6   71      60 non-null     float64
 7   76      95 non-null     float64
dtypes: float64(2), int64(2), object(4)
memory usage: 6.4+ KB

In [4]:
df = df.rename(columns={0: 'UF', 1: 'código_município', 2: 'município', 3: 'código_escola', 
                        4:'escola', 5:'rede', 71:'IDEB_2015', 76: 'Projeção_2015' })
df

,UF,código_município,município,código_escola,escola,rede,IDEB_2015,Projeção_2015
0,PB,2500106,Água Branca,25033158,EMEIF MAE IAIA,Municipal,6.0,5.3
1,PB,2500106,Água Branca,25033557,EMEIF DELFINO JOSE DOS SANTOS,Municipal,6.2,4.3
2,PB,2500106,Água Branca,25033670,EMEF ANTONIO VIRGOLINO BATISTA,Municipal,NaN,5.2
3,PB,2500205,Aguiar,25023489,EEEM AGENOR MENDES PEDROSA,Estadual,NaN,3.7
4,PB,2500205,Aguiar,25023535,EMEIEFCNNM LIDIA CABRAL DE SOUSA,Municipal,NaN,3.9
...,...,...,...,...,...,...,...,...
95,PB,2501203,Areial,25061429,EMGLA GERALDO L DE ARAUJO,Municipal,4.5,4.5
96,PB,2501203,Areial,25061445,E M E F FRANCISCO APOLINARIO DA SILVA,Municipal,5.7,4.0
97,PB,2501203,Areial,25061542,GR ESC EZEQUIEL VIEIRA,Municipal,NaN,5.0
98,PB,2501203,Areial,25061593,GR ESC MODELO,Municipal,5.0,4.7
99,PB,2501203,Areial,25061607,GR ESC SEVERINO BARBOSA,Municipal,4.4,3.5

In [5]:
#Q5
dm = df.query('rede=="Municipal"')
dm

,UF,código_município,município,código_escola,escola,rede,IDEB_2015,Projeção_2015
0,PB,2500106,Água Branca,25033158,EMEIF MAE IAIA,Municipal,6.0,5.3
1,PB,2500106,Água Branca,25033557,EMEIF DELFINO JOSE DOS SANTOS,Municipal,6.2,4.3
2,PB,2500106,Água Branca,25033670,EMEF ANTONIO VIRGOLINO BATISTA,Municipal,NaN,5.2
4,PB,2500205,Aguiar,25023535,EMEIEFCNNM LIDIA CABRAL DE SOUSA,Municipal,NaN,3.9
5,PB,2500205,Aguiar,25023578,EMEF JOANA LACERDA LEITE,Municipal,NaN,5.1
...,...,...,...,...,...,...,...,...
95,PB,2501203,Areial,25061429,EMGLA GERALDO L DE ARAUJO,Municipal,4.5,4.5
96,PB,2501203,Areial,25061445,E M E F FRANCISCO APOLINARIO DA SILVA,Municipal,5.7,4.0
97,PB,2501203,Areial,25061542,GR ESC EZEQUIEL VIEIRA,Municipal,NaN,5.0
98,PB,2501203,Areial,25061593,GR ESC MODELO,Municipal,5.0,4.7
99,PB,2501203,Areial,25061607,GR ESC SEVERINO BARBOSA,Municipal,4.4,3.5

In [6]:
#Q6
df.sort_values('IDEB_2015', ascending= False , inplace=True , ignore_index=True)
df.loc[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], ['município','escola','IDEB_2015']]

,município,escola,IDEB_2015
1,Água Branca,EMEIF MAE IAIA,6.0
2,Areial,E M E F FRANCISCO APOLINARIO DA SILVA,5.7
3,Amparo,ESCOLA M DE EDUCACAO BASICA ILDEFONSO ANSELMO ...,5.3
4,Alagoa Grande,EMEIF PROFESSOR GERALDO COSTA,5.2
5,Alagoa Nova,EMEIEF DR FERNANDO CUNHA LIMA,5.2
6,Aguiar,EMEF DOZINHA BENTO,5.0
7,Areial,GR ESC MODELO,5.0
8,Arara,GR ESC MARIA DO CARMO ALVES DE MORAIS,5.0
9,Alagoa Nova,EEEF PROF CARDOSO,5.0
10,Alagoa Grande,EMEIF JOSE FERREIRA DE PAIVA,5.0
11,Arara,EMEIF JOAQUIM ALVES DA SILVA,4.9
12,Alagoinha,ESC MUL SEVERINO FLAVIANO CAVALCANTE,4.8
13,Aparecida,EMEF SEVERINA FERREIRA DE SOUSA,4.7
14,Alagoa Grande,EEEF DE DEMONSTRACAO ALAGOA GRANDE,4.7
15,Arara,EMEIF MARIA DO CARMO CASTRO,4.6
16,São João do Rio do Peixe,EEEF DE GRAVATA,4.6
17,São João do Rio do Peixe,EEEF CONEGO MANOEL JACOME,4.6
18,Alcantil,ESCOLA MUN ENS FUND JOSE EUZEBIO DA COSTA,4.6
19,Araruna,EDUCANDARIO SAGRADA FAMILIA,4.5
20,Araçagi,EEEF RODRIGUES DE CARVALHO,4.5

In [7]:
#Q7
df.sort_values('IDEB_2015', ascending= True , inplace=True , ignore_index=True)
df.loc[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], ['município','escola','IDEB_2015']]

,município,escola,IDEB_2015
1,Algodão de Jandaíra,EMEF MANOEL ANTONIO COELHO DE ANDRADE,2.9
2,Areia,EMEF JOSE LINS SOBRINHO,3.3
3,Areia de Baraúnas,EMEF ABDIAS JOSE DA COSTA,3.4
4,Alagoa Grande,EMEIF ENEAS CAVALCANTE,3.4
5,Alagoa Nova,EMEIEF E CASA DA CRIANCA MENINO JESUS,3.5
6,Araçagi,EMEF LUIZ BARBOSA,3.5
7,Alhandra,EEEF BARAO DO ABIAI,3.5
8,Alagoa Grande,EMEIF SEVERINO RAMALHO,3.5
9,Alagoa Grande,EMEIF NOSSA SENHORA DE FATIMA,3.5
10,Alhandra,EMEIEF ALFREDO CIPRIANO FERREIRA DA SILVA,3.6
11,Alagoa Grande,EMEIF CANDIDO REGIS DE BRITO,3.7
12,Alhandra,EMEIEF PROF ZELIA CORREIA DO O,3.7
13,Alhandra,EMEIEF ALFREDO JOSE DE CARVALHO,3.7
14,Araçagi,EMEF ALICE DE ALMEIDA CARNEIRO,3.8
15,São João do Rio do Peixe,EMEIEF DR JOSE DANTAS PINHEIRO,3.9
16,Alagoinha,ESC MUN ENS FUND CARLOS MARTINS BELTRAO,3.9
17,Alagoinha,GR MUL JOSE BARBOSA DE LUCENA,3.9
18,Aparecida,EMEF JOAQUINA AMELIA DE SA,4.1
19,Alhandra,EMEIEF CREUZA RAQUEL PEREIRA GENUARIO NUNES,4.1
20,Alhandra,EMEIEF ADAUTO FERREIRA DE PAULA,4.1

In [8]:
#Q8
df['eficacia']=df['IDEB_2015'] / df['Projeção_2015']
df

,UF,código_município,município,código_escola,escola,rede,IDEB_2015,Projeção_2015,eficacia
0,PB,2500403,Alagoa Nova,25114387,EMEIEF PROFESSORA MARIA LUIZA DE AQUINO,Municipal,2.6,3.2,0.812500
1,PB,2500577,Algodão de Jandaíra,25057898,EMEF MANOEL ANTONIO COELHO DE ANDRADE,Municipal,2.9,4.0,0.725000
2,PB,2501104,Areia,25064410,EMEF JOSE LINS SOBRINHO,Municipal,3.3,3.9,0.846154
3,PB,2501153,Areia de Baraúnas,25020609,EMEF ABDIAS JOSE DA COSTA,Municipal,3.4,3.9,0.871795
4,PB,2500304,Alagoa Grande,25063120,EMEIF ENEAS CAVALCANTE,Municipal,3.4,4.2,0.809524
...,...,...,...,...,...,...,...,...,...
95,PB,2501104,Areia,25106694,EMEF PROFESSOR ABEL BARBOSA DA SILVA,Municipal,NaN,4.8,NaN
96,PB,2501153,Areia de Baraúnas,25020374,EEEFM CLOVIS SATIRO,Estadual,NaN,3.6,NaN
97,PB,2501203,Areial,25061402,EEEFM FRANCISCO A SILVA,Estadual,NaN,4.4,NaN
98,PB,2501203,Areial,25061410,EEEF INACIO GONDIM,Estadual,NaN,4.8,NaN
99,PB,2501203,Areial,25061542,GR ESC EZEQUIEL VIEIRA,Municipal,NaN,5.0,NaN

In [9]:
#retirei os NaN
import numpy as np
df=df.replace(np.nan,0)
df

,UF,código_município,município,código_escola,escola,rede,IDEB_2015,Projeção_2015,eficacia
0,PB,2500403,Alagoa Nova,25114387,EMEIEF PROFESSORA MARIA LUIZA DE AQUINO,Municipal,2.6,3.2,0.812500
1,PB,2500577,Algodão de Jandaíra,25057898,EMEF MANOEL ANTONIO COELHO DE ANDRADE,Municipal,2.9,4.0,0.725000
2,PB,2501104,Areia,25064410,EMEF JOSE LINS SOBRINHO,Municipal,3.3,3.9,0.846154
3,PB,2501153,Areia de Baraúnas,25020609,EMEF ABDIAS JOSE DA COSTA,Municipal,3.4,3.9,0.871795
4,PB,2500304,Alagoa Grande,25063120,EMEIF ENEAS CAVALCANTE,Municipal,3.4,4.2,0.809524
...,...,...,...,...,...,...,...,...,...
95,PB,2501104,Areia,25106694,EMEF PROFESSOR ABEL BARBOSA DA SILVA,Municipal,0.0,4.8,0.000000
96,PB,2501153,Areia de Baraúnas,25020374,EEEFM CLOVIS SATIRO,Estadual,0.0,3.6,0.000000
97,PB,2501203,Areial,25061402,EEEFM FRANCISCO A SILVA,Estadual,0.0,4.4,0.000000
98,PB,2501203,Areial,25061410,EEEF INACIO GONDIM,Estadual,0.0,4.8,0.000000
99,PB,2501203,Areial,25061542,GR ESC EZEQUIEL VIEIRA,Municipal,0.0,5.0,0.000000

In [10]:
#Q9
df['maior_0.80']=df['eficacia']>0.80
df

,UF,código_município,município,código_escola,escola,rede,IDEB_2015,Projeção_2015,eficacia,maior_0.80
0,PB,2500403,Alagoa Nova,25114387,EMEIEF PROFESSORA MARIA LUIZA DE AQUINO,Municipal,2.6,3.2,0.812500,True
1,PB,2500577,Algodão de Jandaíra,25057898,EMEF MANOEL ANTONIO COELHO DE ANDRADE,Municipal,2.9,4.0,0.725000,False
2,PB,2501104,Areia,25064410,EMEF JOSE LINS SOBRINHO,Municipal,3.3,3.9,0.846154,True
3,PB,2501153,Areia de Baraúnas,25020609,EMEF ABDIAS JOSE DA COSTA,Municipal,3.4,3.9,0.871795,True
4,PB,2500304,Alagoa Grande,25063120,EMEIF ENEAS CAVALCANTE,Municipal,3.4,4.2,0.809524,True
...,...,...,...,...,...,...,...,...,...,...
95,PB,2501104,Areia,25106694,EMEF PROFESSOR ABEL BARBOSA DA SILVA,Municipal,0.0,4.8,0.000000,False
96,PB,2501153,Areia de Baraúnas,25020374,EEEFM CLOVIS SATIRO,Estadual,0.0,3.6,0.000000,False
97,PB,2501203,Areial,25061402,EEEFM FRANCISCO A SILVA,Estadual,0.0,4.4,0.000000,False
98,PB,2501203,Areial,25061410,EEEF INACIO GONDIM,Estadual,0.0,4.8,0.000000,False
99,PB,2501203,Areial,25061542,GR ESC EZEQUIEL VIEIRA,Municipal,0.0,5.0,0.000000,False

In [11]:
#Q10
df['maior_1']=df['eficacia']>=1
df

,UF,código_município,município,código_escola,escola,rede,IDEB_2015,Projeção_2015,eficacia,maior_0.80,maior_1
0,PB,2500403,Alagoa Nova,25114387,EMEIEF PROFESSORA MARIA LUIZA DE AQUINO,Municipal,2.6,3.2,0.812500,True,False
1,PB,2500577,Algodão de Jandaíra,25057898,EMEF MANOEL ANTONIO COELHO DE ANDRADE,Municipal,2.9,4.0,0.725000,False,False
2,PB,2501104,Areia,25064410,EMEF JOSE LINS SOBRINHO,Municipal,3.3,3.9,0.846154,True,False
3,PB,2501153,Areia de Baraúnas,25020609,EMEF ABDIAS JOSE DA COSTA,Municipal,3.4,3.9,0.871795,True,False
4,PB,2500304,Alagoa Grande,25063120,EMEIF ENEAS CAVALCANTE,Municipal,3.4,4.2,0.809524,True,False
...,...,...,...,...,...,...,...,...,...,...,...
95,PB,2501104,Areia,25106694,EMEF PROFESSOR ABEL BARBOSA DA SILVA,Municipal,0.0,4.8,0.000000,False,False
96,PB,2501153,Areia de Baraúnas,25020374,EEEFM CLOVIS SATIRO,Estadual,0.0,3.6,0.000000,False,False
97,PB,2501203,Areial,25061402,EEEFM FRANCISCO A SILVA,Estadual,0.0,4.4,0.000000,False,False
98,PB,2501203,Areial,25061410,EEEF INACIO GONDIM,Estadual,0.0,4.8,0.000000,False,False
99,PB,2501203,Areial,25061542,GR ESC EZEQUIEL VIEIRA,Municipal,0.0,5.0,0.000000,False,False